version: '3.8'  # Or the latest version you prefer

services:
  mongodb:
    image: mongo:latest  # Use 'mongo:latest-alpine' for the Alpine version
    container_name: ecom-mongo  
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: testpassword